apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: istio-issuer
  namespace: istio-system
  annotations:
     cert-manager.io/certificate-name: istio-ca
spec:
  ca:
    secretName: istio-certmanager-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # This will register an issuer with LetsEncrypt.  Replace
    # with your admin email address.
    email: costin@google.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        clouddns:
          # Set this to your GCP project-id
          project: dmeshgate
          # Set this to the secret that we publish our service account key
          # in the previous step.
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-issuer
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
       ingress:
         class: istio

# kubectl edit cm config-domain --namespace knative-serving
# cr.webinf.info: ""

#kubectl edit configmap config-network --namespace knative-serving
#  autoTLS: Enabled

#kubectl apply -f https://raw.githubusercontent.com/knative/docs/master/docs/serving/autoscaling/autoscale-go/service.yaml
# kubectl get service.serving.knative.dev -A

#kubectl apply --filename https://github.com/knative/net-certmanager/releases/download/v0.20.0/release.yaml


# Automatic doesn't seem to work - probably ingress class issues
# kubectl delete --filename https://github.com/knative/net-certmanager/releases/download/v0.20.0/release.yaml
# kubectl edit configmap config-certmanager --namespace knative-serving

#----
#
#apiVersion: cert-manager.io/v1alpha2
#kind: Certificate
#metadata:
#  name: istiod
#  namespace: istio-system
#spec:
#  secretName: istiod
#  issuerRef:
#    name: istio-issuer
#    kind: Issuer
#  commonName: istiod.istio-system.svc
#  dnsNames:
#  - istiod.istio-system.svc

---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: autoscale-go
#  namespace: istio-system
#spec:
#  secretName: autoscale-go
#  issuerRef:
#    name: letsencrypt-http01-issuer
#    kind: ClusterIssuer
#  commonName: autoscale-go.default.cr.webinf.info
#  dnsNames:
#  - autoscale-go.default.cr.webinf.info
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: autoscale-go-i2
  namespace: istio-system
spec:
  secretName: autoscale-go-i2
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  commonName: yautoscale-go.default.i2.webinf.info
  dnsNames:
  - yautoscale-go.default.i2.webinf.info
#  acme:
#    config:
#    - http01:
#        ingressClass: istio
#      domains:
#      - yautoscale-go.default.i2.webinf.info

---

# Not created automatically in add-on !

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateay
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istiod-knative
  namespace: istio-system
spec:
  secretName: istiod-knative
  issuerRef:
    name: letsencrypt-dns-issuer
    kind: ClusterIssuer
  commonName: istiod-knative.istio-sysytem.cloudrun.i.webinf.info
  dnsNames:
  - istiod-knative.istio-sysytem.cloudrun.i.webinf.info
