apiVersion: skaffold/v3
kind: Config
metadata:
  name:	session

manifests:
  kustomize:
    paths:
      - "."

deploy:
    kubectl: {}

portForward:
  - resourceType: Service
    resourceName: gateway
    port: 8080
    localPort: 9880
