---
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iperf3-cli
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - image: docker.io/networkstatic/iperf3
        imagePullPolicy: IfNotPresent
        name: iperf3
        ports:
        - containerPort: 5201
        args:
        - '-c'
        - 'iperf3'
        resources:
          requests:
            cpu: 1000m
            memory: "1G"
          limits:
            cpu: 1000m
            memory: "2G"
