apiVersion: skaffold/v1
kind: Config
metadata:
  name:    istio-gw-hostport
deploy:
  helm:
    releases:
      - name: istio-gw-hostport
        chartPath: .
        namespace: istio-gw-hostport
portForward:
  - resourceType: daemonset
    namespace: istio-gw-hostport
    resourceName: istio-gw-hostport
    port: 15000
    localPort: 12000
