---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: kube-registry
#  namespace: istio-gw-hostport
#spec:
#  host: kube-registry.kube-registry.svc.cluster.local
#  trafficPolicy:
#    tls:
#      mode: DISABLE

