---
---
# This is really :443 on the host
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gate15443
spec:
  selector:
    istio: {{ .Release.Namespace }}
  servers:
    - hosts:
        - "./*"
      port:
        name: https
        number: 15443
        # Must have TLS config
        protocol: HTTPS
{{/*      tls:*/}}
{{/*        mode: SIMPLE*/}}
{{/*        privateKey: /etc/istio/proxy/key.pem*/}}
{{/*        serverCertificate: /etc/istio/proxy/cert-chain.pem*/}}
{{/*        caCertificates: /etc/istio/proxy/root-cert.pem*/}}
---
# :80 on the host
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gate
spec:
  selector:
    istio: {{ .Release.Namespace }}
  servers:
    - hosts:
        - "./*"
      port:
        name: http
        number: 15080
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gate5228
spec:
  selector:
    istio: {{ .Release.Namespace }}
  servers:
    - hosts:
        - "./*"
      port:
        name: tcp-wps
        number: 5228
        protocol: TCP

