# Example Service object.
# To migrate to the new charts, apply this object first, so
# the Service object is no longer treated as helm-managed.
apiVersion: v1
kind: Service
metadata:
  # The service is named based on the release name
  # For istio-system, the release should be named istio-ingressgateway.
  name: {{ .Release.Name }}

  # Any annotations from gateway.serviceAnnotations go here
  #annotations:

spec:
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- if .Values.externalTrafficPolicy }}
  externalTrafficPolicy: {{.Values.externalTrafficPolicy }}
  {{- end }}
  type: {{ .Values.type }}

  selector:
    {{ if .Values.selector }}
    istio: {{ .Values.selector }}
    {{ else }}
    istio: {{ .Release.Name }}
    {{ end }}
  # Note that AWS ELB will by default perform health checks on the first port
  # on this list. Setting this to the health check port will ensure that health
  # checks always work. https://github.com/istio/istio/issues/12503
  ports:
    # In older Istio releases ( 1.4 ), statusPort was
    # 15020 - upgrading won't work with 15021
    - port: {{ .Values.statusPort}}
      name: status-port
      protocol: TCP
    - port: 80
      targetPort: 8080
      name: http2
      protocol: TCP
    - port: 443
      targetPort: 8443
      name: https
      protocol: TCP
    # East-West gateway
    - name: tls
      port: 15443
      targetPort: 15443
    - name: tls-istiod
      port: 15012
      targetPort: 15012
    - name: tls-webhook
      port: 15017
      targetPort: 15017
    # Additional ports
    - port: 5000
      name: http2-registry
      protocol: TCP
    - port: 8002
      name: http2-k8s-gw
      protocol: TCP
    - port: 8003
      name: tls-k8s-gw
      protocol: TCP

---
