#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: kube-system-kube-registry-pv
#  labels:
#    kubernetes.io/cluster-service: "true"
#spec:
#capacity:
#  storage: 100Gi
#accessModes:
#  - ReadWriteOnce
#gcePersistentDisk:
#  pdName: registry
#  fsType: "ext4"

# storage class optional, cluster default
# gce default: ext4
# Creating a PersistentVolumeClaim automatically creates the PV

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-registry
  namespace: istio-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

# deployment strategy must chang
