apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-registry
  namespace: istio-system
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
