apiVersion: v1
name: istio
version: 0.5.0
description: Gateway hosts configuration.
keywords:
  - istio
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
