apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: httpbin
  labels:
    selected: "yes"
spec:
  hostnames: ["httpbin.example.com"]
  rules:
    - matches:
        - path:
            type: Prefix
            value: /get
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              my-added-header: added-value
      forwardTo:
        - serviceName: httpbin
          port: 8000
