
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-http
spec:
  selector:
    istio: {{ .Release.Name }}
  servers:
    - hosts:
        - "./*"
      port:
        name: http
        number: 80
        protocol: HTTP

