# Example Service object.
# To migrate to the new charts, apply this object first, so
# the Service object is no longer treated as helm-managed.
apiVersion: v1
kind: Service
metadata:
  {{- if eq .Release.Namespace "istio-system" }}
  name: istio-ingressgateway
  {{- else }}
  # The service is named based on the release name
  name: istio-{{ .Release.Namespace }}
  {{- end }}

  # Any annotations from gateway.serviceAnnotations go here
  #annotations:

  labels:
    istio: {{ .Release.Namespace }}-{{ .Release.Name }}

spec:
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- if .Values.externalTrafficPolicy }}
  externalTrafficPolicy: {{.Values.externalTrafficPolicy }}
  {{- end }}
  type: {{ .Values.type }}

  selector:
    {{- if eq .Release.Namespace "istio-system"}}
    istio: ingressgateway
    {{- else }}
    istio: {{ .Release.Namespace }}
    {{- end }}
  # Note that AWS ELB will by default perform health checks on the first port
  # on this list. Setting this to the health check port will ensure that health
  # checks always work. https://github.com/istio/istio/issues/12503
  ports:
    # In older Istio releases ( 1.4 ), statusPort was
    # 15020 - upgrading won't work with 15021
    - port: {{ .Values.statusPort}}
      name: status-port
      protocol: TCP
    - port: 80
      targetPort: 8080
      name: http2
      protocol: TCP
    - port: 443
      targetPort: 8443
      name: https
      protocol: TCP
---
