# This file controls the ports exposed by ingress gateway

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-local-gateway
  namespace: istio-system
  labels:
    app: cluster-local-gateway
spec:
  type: ClusterIP
  selector:
    app: cluster-local-gateway
  ports:
    -
      name: http2
      port: 80
      targetPort: 80
    -
      name: https
      port: 443
    -
      name: tls
      port: 15443
      targetPort: 15443

---

# Main Gateway. Apps must bind to NAMESPACE/ingressgateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cluster-local-gateway
  namespace: istio-system
spec:
  selector:
    istio: cluster-local-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
      # Additional ports in gateaway for the ingressPorts - apps using dedicated port instead of hostname
    - port:
        number: 15012
        protocol: TCP
        name: tcp-pilot
      hosts:
        - "*"
