#apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fortio
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
    - host: fortio.{{ .Values.domain }}
      http:
        paths:
          - path: /.*
            backend:
              serviceName: fortio
              servicePort: 8080
