apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: istio-gate-config-all
deploy:
  helm:
    releases:
    - name: istio-gate-config-all
      chartPath: .
      namespace: istio-system
    - name: istio-gate-config-all
      chartPath: .
      namespace: istio-gate
portForward:
- resourceType: daemonset
  resourceName: istio-gw-hostport
  namespace: istio-gw-hostport
  port: 15000
  localPort: 12000
- resourceType: replicationcontroller
  resourceName: kube-registry-v0
  namespace: kube-registry
  port: 5000
  localPort: 5000
- resourceType: service
  resourceName: kube-registry
  namespace: kube-registry
  port: 5000
  localPort: 5001
