---
# Runs a docker-mounted dev image.
# Can build images in the node's docker.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-istiod
  labels:
    app: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
      annotations:
        sidecar.istio.io/proxyImage: gcr.io/istio-testing/proxyv2:latest
    spec:
      terminationGracePeriodSeconds: 1
      #securityContext:
      #  runAsUser: 1000
      containers:
        - name: app
          image: gcr.io/istio-testing/build-tools:master-latest
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: PORT
              value: "8080"
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
            - name: HUB
              value: costinm
            - name: BUILD_WITH_CONTAINER
              value: "0"
          volumeMounts:
{{/*            # No longer works. - using DIND instead */}}
{{/*            - mountPath: /var/run/docker.sock*/}}
{{/*              name: docker-socket-volume*/}}

            - mountPath: /work
              name: src


            - name: podinfo
              mountPath: /etc/istio/pod

            # Istio secrets (for istio-system)
            - mountPath: /var/run/secrets/istio
              name: istiod-ca-cert
            - name: istio-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              name: https
              protocol: TCP
        - name: dind
          image: docker:18.05-dind
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
              - NET_ADMIN
            privileged: true
          ports:
            - containerPort: 2375
              name: dind
              protocol: TCP
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker


      volumes:
        - name: envcfg
          configMap:
            name: codeenv
            optional: true

{{/*        - name: docker-socket-volume*/}}
{{/*          hostPath:*/}}
{{/*            path: /var/run/docker.sock*/}}
{{/*            type: File*/}}

        - name: src
          persistentVolumeClaim:
            claimName: istio-src
        #        - name: dind-storage
        #          emptyDir: {}
        - name: dind-storage
          persistentVolumeClaim:
            claimName: dind

        - name: istiod-ca-cert
          configMap:
            name: istio-ca-root-cert
            optional: true

        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations

        - name: istio-token
          projected:
            sources:
              - serviceAccountToken:
                  path: istio-token
                  expirationSeconds: 43200
                  audience: istio-ca

