apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  egress:
    - hosts:
        - "./*"
        - "{{ .Values.global.telemetryNamespace }}/*"
        - "{{ .Values.global.policyNamespace }}/*"
        - httpbin/*
