apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - gateway-ilb.yaml
  - routes.yaml
  - service.yaml
  - app-v1.yaml
  - app-v2.yaml
  - client.yaml

namespace: session2

#commonLabels:
#  app: istiod-debug

#nameSuffix: -debug


#images:
#  - name: gcr.io/istio-testing/istiod
#    newName: gcr.io/costin-istio/istiod

