apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  selector:
    app: echo
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 18080
  - name: grpc
    port: 7070
    targetPort: 17070
  - name: tcp
    port: 9090
    targetPort: 19090
---

