apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-cpp
    istio.io/persistent-session: grpc-session-cookie
  name: echo-cpp
spec:
  selector:
    app: echo-cpp
  type: ClusterIP
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
