
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-cpp
    istio.io/persistent-session: grpc-session-cookie
  name: echo-cpp-grpc-v2
spec:
  selector:
    app: echo-cpp
    version: v2
  type: ClusterIP
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: echo-cpp-grpc-v2
spec:
  selector:
    matchLabels:
      app: echo-cpp
      version: v2
  portLevelMtls:
    8080:
      mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo-cpp-grpc-v2
spec:
  host: echo-cpp-grpc-v1.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-cpp-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-cpp
      version: v2
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      labels:
        sidecar.istio.io/inject: "true"
        app: echo-cpp
        version: v2
    spec:
      containers:
        - env:
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: GRPC_VERBOSITY
              value: "DEBUG"
            - name: GRPC_TRACE
              value: "xds_client,xds_resolver,xds_cluster_manager_lb,cds_lb,eds_lb,xds_cluster_resolver_lb,priority_lb,xds_cluster_impl_lb,weighted_target_lb,lrs_lb,xds_server_config_fetcher"
          #image: costinm/interop-server:latest
          image: grpctesting/istio_echo_cpp:v1.54.0
          imagePullPolicy: Always
          name: app
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            runAsGroup: 1338
            runAsUser: 1338
---
