
# This is based on Frank's sample, with extra comments and updated port numbers.
# The json variant is included in envoy_bootstrap.json, and can be used in envoy filters
# for bootstrap.
static_resources:
  listeners:
    # hbone_h2c unwraps the TCP stream from the HTTP/2 stream
    # This is the HBONE over plaintext port, forwarding to local_tcp_8443 cluster, which
    # forwards to listener_2
    - name: hbone_h2c
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 15009
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/_hbone/mtls"
                            headers:
                              - name: ":method"
                                exact_match: "POST"
                          route:
                            cluster: local_mtls
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config:
                                  allow_post: true
                http_filters:
                  - name: envoy.filters.http.router
                http2_protocol_options:
                  allow_connect: true

    # listener_2 decrypts the mTLS TCP stream into a raw TCP stream.
    - name: mtls
      address:
        socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 8443
      filter_chains:
        - filters:
            - name: tcp
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_stats
                cluster: local_8080
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  certificate_chain: { "filename": "/etc/certs/cert.pem" }
                  private_key: { "filename": "/etc/certs/key.pem" }

  clusters:
    # local_mtls is the cluster for HBONE /_hbone/mtls - forwading to the mTLS local listener
    - name: local_mtls
      connect_timeout: 2s
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:
              allow_connect: true
      load_assignment:
        cluster_name: local_mtls
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8443

    # cluster_2 proxies the raw TCP stream to the TCP server.
    - name: local_8080
      connect_timeout: 2s
      load_assignment:
        cluster_name: local_8080
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7777
