# Installs istiod. This is a clean(er) template, no helm used.
# Intended for CI/CD and humans - can be used with kustomize or other tools to patch it.
#
# "cluster" resources must be applied first, with admin priviledge
# "autoinject" should be applied after, if you want auto-injection webhook.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-mesh.yaml
  - configmap-injection.yaml
  - istiod.yaml
