apiVersion: v1
kind: Service
metadata:
  name: fortio
  namespace: session2
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "fortio"}'
  labels:
    istio.io/persistent-session: GCILB

spec:
  ports:
    - port: 8080
      name: http-echo
    - port: 8081
      name: grpc-echo
    # No selector
---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: fortio
spec:
  connectionDraining:
    drainingTimeoutSec:
      60
  timeoutSec: 40
  sessionAffinity:
    affinityType: "CLIENT_IP"
  customRequestHeaders:
    headers:
      - "X-Client-Region:{client_region}"
      - "X-Client-City:{client_city}"
      - "X-Client-CityLatLong:{client_city_lat_long}"
  logging:
    enable: true
    sampleRate: 0.5

  # CloudArmor
#  securityPolicy:
#    name: "example-security-policy"
#  healthCheck:
#    checkIntervalSec: INTERVAL
#    timeoutSec: TIMEOUT
#    healthyThreshold: HEALTH_THRESHOLD
#    unhealthyThreshold: UNHEALTHY_THRESHOLD
#    type: PROTOCOL
#    requestPath: PATH
#    port: PORT
