# Istiod checks if the gateway SA has list permission
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-lister
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-secret-lister
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-lister
subjects:
  - kind: ServiceAccount
    name: default
