{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
