apiVersion: v1
name: fortio
version: 1.1.0
tillerVersion: ">=2.7.2"
description: Helm chart for fortio deployment
keywords:
  - istio
  - fortio
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
