{{- range $index, $d := .Values.domains }}

{{ if $d.serviceName }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $d.name }}-http
spec:
  selector:
    istio: {{ $.Values.selector }}
  servers:
    - hosts:
        - "./{{ $d.domain }}"
      port:
        name: http
        number: 80
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $d.name }}-https
spec:
  selector:
    istio: {{ $.Values.selector }}
  servers:
    - hosts:
        - "./{{ $d.domain }}"
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: cert-{{ $d.name }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $d.name }}
spec:
  hosts:
    - {{ $d.domain }}
  gateways:
    - {{ $d.name }}-http
    - {{ $d.name }}-https
  http:
    - route:
        - destination:
            host: {{ $d.serviceName }}
            port:
              number: {{ $d.port }}
  {{ end }}
  {{ end }}
