{{ if .Values.wildcardDomain }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istiod-sub
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        # use a valid credential here
        credentialName: {{ .Values.cert }}
      hosts:
      - "istiod.{{ .Values.wildcardDomain }}"
    - port:
        name: https
        number: 15012
        protocol: HTTPS
      tls:
        mode: MUTUAL
        # use a valid credential here
        credentialName: {{ .Values.cert }}
      hosts:
        - "istiod.{{ .Values.wildcardDomain }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istiod-sub-vs
spec:
  hosts:
  - "istiod.{{ .Values.wildcardDomain }}"
  gateways:
  - istiod-sub
  http:
  - match:
    -  uri:
        prefix: /inject/
    route:
    - destination:
        host: istiod-{{ .Values.revision }}.istio-system.svc.cluster.local
        port:
          number: 443
  - match:
    -  uri:
        prefix: /envoy.service.discovery.v3.AggregatedDiscoveryService
    route:
    - destination:
        host: istiod-{{ .Values.revision }}.istio-system.svc.cluster.local
        port:
          number: 15012
  - match:
      -  uri:
           prefix: /istio.v1.auth.IstioCertificateService/
    route:
      - destination:
          host: istiod-{{ .Values.revision }}.istio-system.svc.cluster.local
          port:
            number: 15012
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istiod-sub-dr
spec:
  host: istiod-{{ .Values.revision }}.istio-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15012
      tls:
        mode: SIMPLE
      connectionPool:
        http:
          h2UpgradePolicy: UPGRADE        
    - port:
        number: 443
      tls:
        mode: SIMPLE
{{ end }}
