apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}

spec:
  type: LoadBalancer
  selector:
    istio: ingressgateway
  ports:
    - port: 15021
      name: status-port
      protocol: TCP
    - port: 80
      targetPort: 8080
      name: http2
      protocol: TCP
    - port: 443
      targetPort: 8443
      name: https
      protocol: TCP
    # Additional ports
{{/*    - port: 5000*/}}
{{/*      name: http2-registry*/}}
{{/*      protocol: TCP*/}}
{{/*    - port: 6000*/}}
{{/*      name: grpc-test*/}}
{{/*      protocol: TCP*/}}
    # East-West gateway
    - name: tls
      port: 15443
      targetPort: 15443
    - name: tls-istiod
      port: 15012
      targetPort: 15012
    - name: tls-webhook
      port: 15017
      targetPort: 15017

