apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-http
spec:
  selector:
    istio: {{ .Values.selector }}
  servers:
    - hosts:
        - "./*"
      port:
        name: http
        number: 8080
        protocol: HTTP
---
{{ if eq .Release.Namespace "istio-system"}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateay
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 8080
        protocol: HTTP

{{ end }}
---
