apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    release: istiod
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway

  ports:
    - port: 80
      name: http
    - port: 443
      name: https

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    release: istiod
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  template:
    metadata:
      labels:
        app: istio-ingressgateway
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istiod
      containers:
        - name: istio-proxy
          image: gcr.io/costin-istio/proxyv2:latest
          args:
            - proxy
            - router
          env:
            - name: CA_ADDR
              value: istiod.istio-system.svc:15012
