apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istiod-sidecar-injector
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istiod
        namespace: istio-system
        path: "/inject"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUw2cmRmWlZMY0dKQmhhMkpkMENVT2N3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1ptUTVZbVEyTkRVdE9XSTRZeTAwTlRJekxXSTROMk10TVRaak1XUmhaVEptWkdGbApNQjRYRFRFM01UQXdOakl4TWpFek1sb1hEVEl5TVRBd05USXlNakV6TWxvd0x6RXRNQ3NHQTFVRUF4TWtabVE1ClltUTJORFV0T1dJNFl5MDBOVEl6TFdJNE4yTXRNVFpqTVdSaFpUSm1aR0ZsTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBb0ZId3R3SVB2aWZkMVQxVSt3MVJERDRvSmNmdkVjNHNYMjEwUXBXSwptWGJsa1h2WlJWb0tIUE5nVFoxUEdYbDlFcE9rRWxoQ0VLMXphUU5HU0U2eXpBOFAyeHhKVHlDSGRZNkU5NFJTCjRqMUJITWNzZTBWQTZENW5RZFRKRWx2Ymp0L2xhUzNNQWNVeHpjREErWnJsY0hCazZ6NHhodktLaHdBWnVCWDAKOWdHb1VzOGR3ZlNuTm5LVmpWWk1BUFpTaklBMDdlaHFpNUdDMHRzcElXL0M4YU13MFUzMkRCY3FNOVlSbzhVRQpFa2trZlZrTDBGT1VXb1YrV0xNRVZPcUVlZytHSHVOdC9ua0RZbTV0dytONXh0bGlqaGtKVy9FV2FoemlTdWhOClBsUjJuZVlwalBxODNPSnJ5Zy9leTlvZmZ4M3k4RmlkdDZ6U1J5elY2VXdqUVFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQplekRleEVrbSt4bnFpMEdreUYydU11UElhL1Z1SUxOMFdERjdMODJrdHM4NHJYbTljR1ZEK0F6M1RTNG54a1pJCjN3eWRieFhxeUtJWDZJMEZxSHRFR2dqNW5hNWxzVU5VK3hldmVnb2JMUGhTd1RLemFQdEV6aCs4V2xtSjFvOHUKdVJoOXEvU0QzaEZrRXljeEJRK0FxcjlCUk03Z2xJSzZpY05MbGw4NDBNNlVVekxGc2s0cVEreENpdmxFN2hpUApNNHpEZWJDWWVUTGN6SEJ2T0p3WE9HZWNxZi9CY3ZKamZwL2lON0VOcEhiUURyMVA2by96aXUzOExsNHZpY3BECkVxTWI4c3MxaG5sMnpicHU0WThmbmRKU0NwRTV1UFo2OE9KekpkaklkcCtPWU9FZVB1QklFd3RJTVp4VlZqNGEKb2VKUlhFb0ZQaXUvVEw5T3FSYmNJQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-env: istiod
