# WIP: compose file to start local docker containers for VM testing, using a k3s server.
# Will create a kubeconfig.yaml file that can be used for debugging.

version: '3'
services:
  k8s:
    image:  rancher/k3s:latest
    ports:
      - "6443:6443"
      - "6080:80"
    privileged: true
    command: server --https-listen-port 6443
    environment:
      - K3S_KUBECONFIG_OUTPUT=/conf/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - .:/conf
      - k3s-server:/var/lib/rancher/k3s

  # TODO: script to wait for k8s to be ready, apply CRDs and start istiod at the end.
  # Istiod container, as a standalone binary running in a docker container outside K8S
  istiod:
    ports:
      - "14010:13010"
    image: costinm/istiod
    environment:
      - KUBECONFIG=/conf/kubeconfig.yaml
    volumes:
      - .:/conf
    links:
    - k8s
    depends_on:
      - k8s

  fortio:
    ports:
      - "14080:8080"
    volumes:
    - conf:/var/log
    image: fortio/fortio
    links:
    - istiod

   # TODO: add the sidecar for fortio


volumes:
  conf: {}
  k3s-server: {}
