
certmanager:
  enabled: true
  email: costin@webinf.info
  commonName: ingress.v10.istio.webinf.info
  certificates:
    - "ingress.v10.istio.webinf.info"


##### Config for pilot

meshNetworks:
  networks:
    weekly10:
      gateways:
        - address: 35.224.222.243
          port: 15443
      endpoints:
        - fromRegistry: weekly10
    costin11:
      gateways:
        - address: 35.236.6.124
          port: 15443
      endpoints:
        - fromRegistry: costin11
