apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istiod-asm
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istiod-asm
        namespace: istio-system
        path: "/inject"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQVBuVitZcTkvQ001eGtNUTg0bDVwNFV3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pUVXpPREV3WkdRdFlURmhOaTAwWW1SbUxXRXdZelF0Tm1SaVlXWmpOekkxTXpReApNQjRYRFRFNE1USXhPVEl5TkRRMU1Wb1hEVEl6TVRJeE9ESXpORFExTVZvd0x6RXRNQ3NHQTFVRUF4TWtaVFV6Ck9ERXdaR1F0WVRGaE5pMDBZbVJtTFdFd1l6UXRObVJpWVdaak56STFNelF4TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM1pJb1FNcktCaTFTTVpLcTN1MHdQZS95RW52dEFGekFxWlRwVyt0agpJeGRiYUNVZ2xML3c2ZmlkMGExSWkvS1F2Qi93YnJkRm9YUmhJTHhvOEdxUU5wL2liMGE4SFRmd3laTkZna0E3CmRhazVRaVdLOTdZMkl3M1hCa3RjbmZhQVdlVGRyYVN0MUx0cXZTalpYeEZPS3Q0cGJNRE5ZaGtENzhaVzlmSjIKTzdhY3RiRmFFb0huc2l6U1BlVEdieHp6NmVwcjBvOXFJS1BZQVc2Z0NrL2VKVHF4cXJDWVlZRi9JQ2tvZmdQQwoyMWhVTTA2ZFBzWkxoaEE4UlBJZ0VnV3V4ZHN3QnYwOW4xQU1sSWNwT1Y3dE9tOThydFJHM2pZN0MrNnUwdlVLCk92QlVRRzhUQWhEM0JDb0xMcklrV1gxSWFzWko3OHNneEQ1azFWZytNd1N5ZVFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpRbXR2MnhNd2I2WVdVQmVxenlDWnBQU3Q0aWZTb09LbnhUUmRMTkxyWGJEUXZkTUhWaTVTQ3VDaHN2Z21yeUxUCkN6cDkwOGhhUGg3V0tDbG9sRDg3ODFYTjJQYnZxTFRiRVA0TTNVWGJ5ZitxNmVCNVh2VHJGMWptSFdHM3dzT3UKak9ndlNLM1lLa244bDhxQWRTblM2aW5pRFdpK2pxYkRZMWpnZlRBenJNck9HNHloQ2txUE1qbmZmanJJV09ESAorOFpNcjBlRGtCTy9jejE5c1VBdktQSm5JUEVNTmdSVlBMelhXT3VhRmxva2lQQ2VDQnRjeU0yRkRTNnpBMVZLCnl3K25wc2kvYm80VlhzbGNvMEdaNXUzd2hSaEJEMzRPZS9UQlBxMTFzK2ZKb3VhSFRmd29VRDE3MjEwRzUzV0QKNE03SHc3cVRkLy94cnM0bi9IOVNBQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        istio-env: asm
