apiVersion: skaffold/v3
kind: Config
metadata:
  name: ambient-stability
deploy:
  helm:
    releases:
    - name: ambient-stability
      chartPath: .
      namespace: ambient-stability
portForward:
- resourceType: deployment
  resourceName: fortio
  namespace: ambient-stability
  port: 8080
  localPort: 11080
