---
apiVersion: v1
kind: Service
metadata:
  name: fortio
spec:
  ports:
    - port: 8080
      name: http-echo
  selector:
    app: fortio

---
apiVersion: v1
kind: Service
metadata:
  name: fortio-cli
spec:
  ports:
    - port: 8080
      name: http-echo
  selector:
    app: cli-fortio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
spec:
  selector:
    matchLabels:
      app: fortio
  replicas: 1
  template:
    metadata:
      annotations:
        # Override container ports
        traffic.sidecar.istio.io/includeInboundPorts: "*"
      labels:
        app: fortio
        version: v1
        istio.io/rev: canary
    spec:
      containers:
      - name: fortio
        image: {{ .Values.fortioImage | default "costinm/fortio:latest" }}
        ports:
         - containerPort: 8080
           name: http
         - containerPort: 8081
           name: grpc
         - containerPort: 8079
        args:
          - server
        resources:
          requests:
            cpu: 10m
            memory: "512Mi"
          limits:
            cpu: "0.1"
            memory: "1G"

