---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-cli
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - image: docker.io/networkstatic/iperf3
        imagePullPolicy: IfNotPresent
        name: iperf3
        ports:
        - containerPort: 5201
        command: ["/bin/sleep","infinity"]

{{/*        - '-c'*/}}
{{/*        - 'iperf3'*/}}
{{/*        - '-t'*/}}
{{/*        - '3600s'*/}}
        resources:
          requests:
            cpu: 100m
            memory: "1G"
          limits:
            cpu: 2000m
            memory: "2G"
