---
apiVersion: v1
kind: Service
metadata:
  name: iperf3
  labels:
    release: {{ .Release.Name }}
spec:
  ports:
  - name: tcp
    port: 5201
    targetPort: 5201
  selector:
    app: iperf3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-srv
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - image: docker.io/networkstatic/iperf3
        imagePullPolicy: IfNotPresent
        name: iperf3
        ports:
        - containerPort: 5201
        args:
        - '-s'
        - '-p'
        - '5201'
        resources:
          requests:
            cpu: 100m
            memory: "1G"
          limits:
            cpu: 2000m
            memory: "2G"
