apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  labels:
    release: {{ .Release.Name }}
spec:
  egress:
    - hosts:
        - "istio-telemetry/*"
        - "istio-policy/*"
