bases:
  # Cluster CRDs and other bases
  - ../../kustomize/cluster
  # Create a sidecar injector mutatingwebhook for non-ASM istiod
  - ../../kustomize/autoinject
  # Create a sidecar injector mutatingwebhook for ASM components
  - ../../test/asm/inject
  
