apiVersion: skaffold/v1
kind: Config
metadata:
  name: kube-registry
deploy:
  helm:
    releases:
      - name: kube-registry
        chartPath: .
        namespace: kube-registry
        #createNamespace: true
#        artifactOverrides:
#          #image: gcr.io/dmeshgate/istiod
#          image: costinm/istiod

portForward:
  - resourceType: replicationcontroller
    namespace: kube-registry
    resourceName: kube-registry-v0
    port: 5000
    localPort: 5000

  # This should not work - it's mtls
  - resourceType: service
    namespace: kube-registry
    resourceName: kube-registry
    port: 5000
    localPort: 5001

