apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istiod-sidecar-injector-cluster
webhooks:
  - name: istiod.istio.io
    clientConfig:
      service:
        name: istiod
        namespace: istio-system
        path: "/inject"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRZWdvMlk2ckdpZ2h6SXlSQnFpSER1REFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNE16Um1aVFJpTWkwek0yVXdMVFF4TnpFdFlqWTFaaTFtTmpBNVkyWTJZMlZqTWpRdwpIaGNOTVRreE1ESTVNakF4T1RBd1doY05NalF4TURJM01qRXhPVEF3V2pBdk1TMHdLd1lEVlFRREV5UTRNelJtClpUUmlNaTB6TTJVd0xUUXhOekV0WWpZMVppMW1OakE1WTJZMlkyVmpNalF3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNhU25lcU5JbXBiem5RY0pnZ21kWlFSVlRhUGtTc0RSSlFZRzFZRXdwKwpscS9xdHIvNlVRZjF0YW1HOGZJWGFXajU2QmdqT0ttZEFkanFRaDVlS0ZOYjZzSXEzaFFZZ3g2Q05tMG55MVNICldsSklZai9IWEUvd04wS3RwdzdSWkI2SVdIeG8yTTRCckdJajhPUUNWSzkyeHNTVWxMcC9MaHgrV0JjMkRzKysKS2VqLzFkSE1ZL29DcXRNZ2t5djBlaVhyb2QxZHdoVFdjM0FEVVdQREVobURZVVVaYTlNQkpiTWt1ZFhGNW9PbQpPS1MvOGRsV0tld1JvcXcrS2FVVEUwa215Rk9DcjFwRXRGRVhpZk1uZ2tBZnpJMTlabGNaWEREN0ZheGpRMkNsCk4vblN3L0VZb09vOExwNHVMc2xqUDJURlEzS2FuMXdkK2dwcjkyc0RZN3lMQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDUgpKTHhTbTh3MHdSYTEzeDZnMktVd29kc2hJYnpvWmZGSzA0aFl2V0t1bGtIYkdMRHptK1oyeGlWVXJQcjA5N0xWCmJjTXJKUHpXMnRnbG1EUDJQRDhQdUJCdEY0RVJkR3R6bzNucDZzMnlJdU96WlZocm1vdjZRL3p6RkVXL21xY0oKVlVETkh0RHE5TGM5cjhjTzJjOXpobW5qbHB0UVpndWE5TGU2L1hJZzVVR0pkcEpBOGxqT1FaQk9MUTJPbEJSMQpZWXRxdHBVaHpTZksxNEpHNUEzRThLMnFTVmRUVkRocWpXQmlVSmFqUWd5RmVNd1NoL1lxVWxHSXBJUXVIN05pCjJldkExVVhnZUFxWGRSYktjOUZuU3g3ODZtenJ0NzB3YTF6djFEaWtBWU83YVNkMDBiaVp3ZnByR1ROdGNBcnIKUytyMEdHMFNzN1Z4NXdaSHhhaFMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: istio-injection
        operator: NotIn
        values:
        - disabled
      - key: istio-env
        operator: DoesNotExist
