# Debug interface is no longer exposed in istiod service. Can also be used with port-forward
apiVersion: v1
kind: Service
metadata:
  name: istiod-debug
  namespace: istio-system
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: istiod
---
