apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: openid-connect
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway

#  url: https://private-bucket/filters/openid.wasm
#  imagePullPolicy: Always

#  url: oci://private-registry:5000/openid-connect/openid:latest
#  imagePullPolicy: IfNotPresent
#  imagePullSecret: private-registry-pull-secret
  url: file:///opt/filters/openid.wasm
  #sha256: 1ef0c9a92b0420cf25f7fe5d481b231464bc88f486ca3b9c83ed5cc21d2f6210

  phase: AUTHN
  pluginConfig:
    openid_server: authn
    openid_realm: ingress
  vmConfig:
    #vm_id: authn

    env:
      - name: POD_NAME
        valueFrom: HOST
      - name: TRUST_DOMAIN
        value: "cluster.local"

  # Also has 'match' to select traffic
---
