apiVersion: v1
kind: Service
metadata:
  name: xds-canary
  namespace: istio-system
spec:
  # Range: 30000-32767
  type: NodePort
  ports:
    - port: 15012
      name: https-dns # mTLS with k8s-signed cert
      nodePort: 32012
    - name: dns-tls
      port: 853
      targetPort: 15053
      protocol: TCP
      nodePort: 32013
    # Debug only - this is not secured
    - port: 15010
      name: grpc-xds # plaintext
      nodePort: 32010
    - name: dns
      port: 53
      targetPort: 15053
      protocol: UDP
      nodePort: 32013
  selector:
    app: istiod
    istio.io/rev: canary
