apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-dns
  namespace: istio-system
data:
  Corefile: |-
    global:15054 {
        errors
        log
        proxy . 127.0.0.1:15053 {
        }

    }

    .:15054 {
        errors
        log
        health :15056 {
          lameduck 5s
        }

        #proxy global 127.0.0.1:15010 {
        #  protocol grpc insecure
        #}
        proxy global 127.0.0.1:15053 {
        }
        proxy svc 127.0.0.1:15053 {
        }
        proxy example.com 127.0.0.1:15053 {
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153

        forward . /etc/resolv.conf
        cache 30
        reload
        loadbalance
    }
