configSources:
  - address: localhost:12901

defaultConfig:
  discoveryAddress: istio-pilot.istio-system:15010

  interceptionMode: REDIRECT

  connectTimeout: 5s
  drainDuration: 45s
  parentShutdownDuration: 1m0s

  envoyMetricsServiceAddress: ""

  proxyAdminPort: 15000
  concurrency: 0

  #proxyAddress: 15001

  statNameLength: 189

  customConfigFile: "conf/sidecar/envoy_bootstrap_v2.json"
